import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, DM_Sans } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/layout/LayoutWrapper.component";
import { cn } from "@/lib/utils";
import { ContextWrapper } from "@/contexts/ContextWrapper";
import { getCurrentUser } from "@/lib/auth-server";
import { fetchCart } from "@/services/cart.service";
import { fetchWishlist } from "@/services/wishlist.service";
import { ThemeProvider } from "@/contexts/ThemeProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const dmSans = DM_Sans({ subsets: ["latin"], variable: "--font-dm-sans", weight: ["400", "500", "600", "700"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Resolve the session on the server so the first HTML already reflects who
  // is signed in. The client never bootstraps auth for itself.
  // The cart and the wishlist are server state too — resolved from the session
  // or their own guest cookies, never from localStorage.
  const [user, cart, wishlistView] = await Promise.all([
    getCurrentUser(),
    fetchCart(),
    fetchWishlist(),
  ]);

  return (
    // next-themes sets `class` and `style="color-scheme"` on <html> from a
    // blocking pre-hydration script, so the server HTML can never match the
    // client. suppressHydrationWarning is scoped to this element's own
    // attributes — children are still checked normally.
    <html
      suppressHydrationWarning
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable, dmSans.variable)}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <ContextWrapper initialUser={user} initialCart={cart} initialWishlist={wishlistView}>
            <LayoutWrapper>{children}</LayoutWrapper>
          </ContextWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
