import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, DM_Sans, Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/layout/LayoutWrapper.component";
import { cn } from "@/lib/utils";
import { ContextWrapper } from "@/contexts/ContextWrapper";
import { getCurrentUser } from "@/lib/auth-server";
import { fetchCart } from "@/services/cart.service";
import { fetchWishlist } from "@/services/wishlist.service";
import { fetchCompare } from "@/services/compare.service";
import { ThemeProvider } from "@/contexts/ThemeProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const dmSans = DM_Sans({ subsets: ["latin"], variable: "--font-dm-sans", weight: ["400", "500", "600", "700"] });

// Every price on this storefront is a Taka sign, and U+09F3 is in the Bengali
// block — no Latin face carries it. DM Sans, Geist and Inter are all
// latin-subset, so `৳7,020` fell through to whatever the OS happened to have:
// a mismatched weight on macOS, Nirmala UI on Windows, and a tofu box on a
// machine with no Bengali font at all.
//
// This sits *after* the Latin face in every font stack below, not before.
// Font fallback is per-glyph: Latin digits and letters still come from DM Sans,
// and only ৳ resolves here. Google serves this face with a Bengali
// unicode-range, so the file is fetched only by a page that actually renders
// one of those code points.
const notoBengali = Noto_Sans_Bengali({ subsets: ["bengali"], variable: "--font-bengali" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Resolve the session on the server so the first HTML already reflects who
  // is signed in. The client never bootstraps auth for itself.
  // The cart and the wishlist are server state too — resolved from the session
  // or their own guest cookies, never from localStorage.
  const [user, cart, wishlistView, compareView] = await Promise.all([
    getCurrentUser(),
    fetchCart(),
    fetchWishlist(),
    fetchCompare(),
  ]);

  return (
    // next-themes sets `class` and `style="color-scheme"` on <html> from a
    // blocking pre-hydration script, so the server HTML can never match the
    // client. suppressHydrationWarning is scoped to this element's own
    // attributes — children are still checked normally.
    <html
      suppressHydrationWarning
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable, dmSans.variable, notoBengali.variable)}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <ContextWrapper initialUser={user} initialCart={cart} initialWishlist={wishlistView} initialCompare={compareView}>
            <LayoutWrapper>{children}</LayoutWrapper>
          </ContextWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
