import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header.component";
import Footer from "@/components/layout/Footer.component";
import LayoutWrapper from "@/components/layout/LayoutWrapper.component";
import { cn } from "@/lib/utils";
import { ContextWrapper } from "@/contexts/ContextWrapper";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <ContextWrapper>
          <LayoutWrapper>{children}</LayoutWrapper>
        </ContextWrapper>
      </body>
    </html>
  );
}
